# **Importing Neccessary Libraries**
---

In [3]:
# --- import Libraries to use their Functions
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- Changing working directory to current folder
file_directory = os.getcwd()
os.chdir(file_directory)

# **Percentiles & Quantiles**
---

In [4]:
reader = pd.read_csv('Titanic-Dataset.csv', chunksize=1000)
titanic_df = pd.concat(reader, ignore_index=True)
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
# --- Cleaning
titanic_df["Age"] = titanic_df["Age"].fillna(titanic_df["Age"].mean())
titanic_df["Fare"] = titanic_df["Fare"].fillna(titanic_df["Fare"].mean())

print(f"Null Attributes in Age:   {int(titanic_df["Age"].isnull().sum())}")
print(f"Null Attributes in Fare:  {int(titanic_df["Fare"].isnull().sum())}")

Null Attributes in Age:   0
Null Attributes in Fare:  0

## **Describe**
---

#### **Describe Whole Dataset**

In [6]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.002015,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,29.699118,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

#### **Describe Specific Columns**

In [7]:
titanic_df[["Age","Fare"]].describe()

              Age        Fare
count  891.000000  891.000000
mean    29.699118   32.204208
std     13.002015   49.693429
min      0.420000    0.000000
25%     22.000000    7.910400
50%     29.699118   14.454200
75%     35.000000   31.000000
max     80.000000  512.329200

## **Percentiles**
---

- Give you a number that describes the value, that a given percent of the values are lower than.

<br/>

<img src="images/Percentiles_&_Quantiles/Percentile-Formula.png" width=550/>

- #### **0-th Percentile**

In [8]:
percentile0 = float(np.percentile(titanic_df["Age"], 0))

print(
    f" 0-th Percentile:  {percentile0}\n"
    f" Minimum Value:    {titanic_df["Age"].min()}"
)

 0-th Percentile:  0.42
 Minimum Value:    0.42

- #### **50-th Percentile**

In [9]:
percentile50 = float(np.percentile(titanic_df["Age"], 50))

print(
    f" 50-th Percentile:  {percentile50}\n"
    f" Median Value:      {titanic_df["Age"].median()}"
)

 50-th Percentile:  29.69911764705882
 Median Value:      29.69911764705882

- #### **100-th Percentile**

In [10]:
percentile100 = float(np.percentile(titanic_df["Age"], 100))

print(
    f" 100-th Percentile:  {percentile100}\n"
    f" Maximum Value:      {titanic_df["Age"].max()}"
)

 100-th Percentile:  80.0
 Maximum Value:      80.0

## **Quantiles**
---

- Quantiles are cut-points that divide a sorted, continuous dataset into equal-sized continuous intervals (or fractions). They express the proportion of data that falls below a given value.

<br/>

<img src="images/Percentiles_&_Quantiles/Quantiles-Formula.png" width=550>

- #### **0-th Quantile**

In [12]:
quantile0 = float(np.quantile(titanic_df["Age"], 0))

print(f" O-th Quantile:  {quantile0}")

 O-th Quantile:  0.42

- #### **25-th Quantile**

In [16]:
quantile25 = float(np.quantile(titanic_df["Age"], 0.25))

print(f" 25-th Quantile:  {quantile25}")

 25-th Quantile:  22.0

- #### **50-th Quantile**

In [18]:
quantile50 = float(np.quantile(titanic_df["Age"], 0.50))

print(f" 50-th Quantile: {quantile50}")

 50-th Quantile: 29.69911764705882

- #### **100-th Quantile**

In [20]:
quantile100 = float(np.quantile(titanic_df["Age"], 1))

print(f" 100-th Quantile:  {quantile100}")

 100-th Quantile:  80.0