# **One-Hot Encoding**
---
<br/>

### **Definition**
---

- One-hot encoding is a simple way to convert text or category labels into numbers (**0s** and **1s**) so that computer and machine learning models can understand them

<br/>

### **Importting Neccessary Libraries**
---

In [26]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

### **Importting Dataset**
---

In [27]:
loan_df = pd.read_csv("loan_data_set.csv")

loan_df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

### **Exploring Data**
---

- To perform One-Hot Encoding, we have to find Categorical attributes (or Columns) like here 'Gender' & 'Married' are Categorical attributes.

In [28]:
loan_df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

### **Filling Null-Values**
---

In [29]:
# --- filling null-values in 'Gender' with mode of 'Gender'
loan_df["Gender"] = loan_df["Gender"].fillna(loan_df["Gender"].mode()[0])

loan_df["Gender"].isnull().sum()

np.int64(0)

In [30]:
# --- filling null-values in 'Married' with mode of 'Married'
loan_df["Married"] = loan_df["Married"].fillna(loan_df["Married"].mode()[0])

loan_df["Married"].isnull().sum()

np.int64(0)

### **One-Hot Encoding**
----

In [31]:
encoding_data = loan_df[["Gender","Married"]]

encoding_data.head()

  Gender Married
0   Male      No
1   Male     Yes
2   Male     Yes
3   Male     Yes
4   Male      No

- #### **Using Pandas (_get_dummies_)**

In [32]:
pd.get_dummies(encoding_data)

     Gender_Female  Gender_Male  Married_No  Married_Yes
0            False         True        True        False
1            False         True       False         True
2            False         True       False         True
3            False         True       False         True
4            False         True        True        False
..             ...          ...         ...          ...
609           True        False        True        False
610          False         True       False         True
611          False         True       False         True
612          False         True       False         True
613           True        False        True        False

[614 rows x 4 columns]

In [33]:
pd.get_dummies(encoding_data).info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  614 non-null    bool
 1   Gender_Male    614 non-null    bool
 2   Married_No     614 non-null    bool
 3   Married_Yes    614 non-null    bool
dtypes: bool(4)
memory usage: 2.5 KB

- #### **Using Scikit-Learn**

In [46]:
ohe = OneHotEncoder()
memory_address = ohe.fit_transform(encoding_data)
memory_address

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1228 stored elements and shape (614, 4)>

In [47]:
arr = memory_address.toarray()
arr

array([[0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       ...,
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]], shape=(614, 4))

In [49]:
pd.DataFrame(arr, columns=["Gender_Female","Gender_Male","Married_Female","Married_Male"])

     Gender_Female  Gender_Male  Married_Female  Married_Male
0              0.0          1.0             1.0           0.0
1              0.0          1.0             0.0           1.0
2              0.0          1.0             0.0           1.0
3              0.0          1.0             0.0           1.0
4              0.0          1.0             1.0           0.0
..             ...          ...             ...           ...
609            1.0          0.0             1.0           0.0
610            0.0          1.0             0.0           1.0
611            0.0          1.0             0.0           1.0
612            0.0          1.0             0.0           1.0
613            1.0          0.0             1.0           0.0

[614 rows x 4 columns]